<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans [
        <!ELEMENT beans (bean)*>
        <!ATTLIST beans
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT bean (property)*>
        <!ATTLIST bean
                class CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                ref CDATA #IMPLIED
                value CDATA #IMPLIED>
        ]>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    <bean id="jimi" class="belajar.spring.domain.Person">
        <property name="nama" value="Jimi Taufik"></property>
        <property name="alamat" ref="jalan"></property>
        <!-- collaborators and configuration for this bean go here -->
    </bean>

    <bean id="dompu" class="belajar.spring.domain.Address">
        <property name="jalan" value="Jl. Lintas Sumbawa Desa Nowa Kec. Woja"></property>
        <property name="kota" value="Dompu NTB"></property>
        <property name="kodePos" value="84251"></property>
        <!-- collaborators and configuration for this bean go here -->
    </bean>

    <!-- more bean definitions go here -->

</beans>